# Preface {.unnumbered}

This is a free book on data in animal welfare 




## Ideas

Louise: Chapter on ethics?

Cynthia: The Excel resources: https://vet.ed.ac.uk/global-agriculture-food-systems/study/farm-data/excel-tutorials 


## Meeting 2nd Feb

Main goals for meeting:

* Flesh out idea
  - We need a chapter on basic stats at least, central tendency and spread, to support the reading of visualisations. 
  - flowcharts on data choices?
  - need to pin down target audience
  - need to write the intro/disclaimer in a way that makes it clear what we are doing, this is not a course that equips you. This guide doesn't cover data management etc. 
  - data collection? Data sources? This might be in the intro?
  - sampling, generalisability, population vs sample, could go together with the data sources or intro? 
  - How do I as a consumer of data react to a histogram? This is a diff audience to people who are dealing with data themselves. 
  - This book is aimed at understanding animal welfare data not processing it 
  - Audience is WORKING in animal welfare but non experts in data 
  - Closing out chapter on applications of data in animal welfare
  - Final case study? You work for Hungry Hedgehogs, this is what you want to report, walk through it?
  - Bad science interpretation?

* Specify chapter list

 - Introduction chapter containing disclaimer, audience pitch, explicit what its not going to cover (e.g. full stats etc)
 - Bad science chapter (Victoria first draft two parts? Build same case study throughout?)
 - sources of data (including a bit of ethics and AI - and remember the aim is you the animal welfare worker needing to use data, you're not collecting it, data quality and source quality, quantity vs quality)
 - Data types  (percentages, noir, prevalence and incidence, groups)
 - tidy data
 - intro to data visualisation (what is a chart why am I looking at it)
 - describing data (central tendncies, spread, transparency??, Victoria)
 - data relationships (highly data vis lean on it)
 - final case study
 - closing applications chapter

* Decide on initial tasks

  - Jill to write a chapter template and word count parameter
  - Jill to look into interactivity
  - Jill to set up a technical meeting
  - Victoria bad science chapter initial draft
  - Jill to make a Teams site for document library purposes
  - Sarah tidy data